// <auto-generated />
using System;
using BoaedgameData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BoardgameData.Migrations
{
    [DbContext(typeof(BoardgameContext))]
    partial class BoardgameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("BoardgameData.Models.Boardgame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.Property<int?>("PlayerId");

                    b.Property<int>("Rating");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Boardgames");
                });

            modelBuilder.Entity("BoardgameData.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("PlayedId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("PlayedId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("BoardgameData.Models.Played", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("Plays");
                });

            modelBuilder.Entity("BoardgameData.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.Property<int?>("PlayedId");

                    b.HasKey("Id");

                    b.HasIndex("PlayedId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BoardgameData.Models.Boardgame", b =>
                {
                    b.HasOne("BoardgameData.Models.Player")
                        .WithMany("Boardgames")
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("BoardgameData.Models.Image", b =>
                {
                    b.HasOne("BoardgameData.Models.Played")
                        .WithMany("Images")
                        .HasForeignKey("PlayedId");
                });

            modelBuilder.Entity("BoardgameData.Models.Player", b =>
                {
                    b.HasOne("BoardgameData.Models.Played")
                        .WithMany("Players")
                        .HasForeignKey("PlayedId");
                });
#pragma warning restore 612, 618
        }
    }
}
